__author__ = 'adriangrepo'

VERSION = "0.10.5a"


BASEPATH = "VelocityModelling/VelocityData/data/"
ISOCALCSPATH = BASEPATH+"IsoCalcs/"
ISOCALCSOUTPUTPATH = ISOCALCSPATH+"Output/"
PLOTSOUTPUTPATH = ISOCALCSOUTPUTPATH+"Plots/"
MISSINGCALCSPATH = BASEPATH+"MissingCalcs/"
DELTACALCSPATH = BASEPATH+"DeltaCalcs/"
TESTDATAPATH = BASEPATH + "TestData/"
ATTRIBCALCSPATH = BASEPATH+"AttributeCalcs/"
ATTRIBCALCSOUTPUTPATH = BASEPATH+"AttributeCalcs/Output/"

TOPS_EXPORT_WELL_HEADER = 'Well'
PETREL_SPREADSHEET_WELL_HEADER = 'Well identifier'
PETREL_SPREADSHEET_ZONE_HEADER = 'Surface'

